### ISSUE TITLE
能否加上录音暂停和播放暂停的功能

### ISSUE THREAD

**Issue by goodbless** [molon/MLAudioRecorder#4]
iOS原生的AVAudioRecorder和Player都有暂停的功能，但rocorder暂停时，player不能播放，反之亦然。您的框架我试了一下，可以实现在录音暂停时，播放录好的部分，然后接着继续录音，但就是缺少暂停的方法。我为了实现功能就自己加了一个，但因为对代码理解不深，不是很放心。还是希望您在正式版本中能添加上这个常用的功能

**Comment by molon** [comment]
@goodbless 我可能不是太理解你的需求。但是库里 recorder和player都是有stop方法的呀。

**Comment by goodbless** [comment]
stop是停止，一般是指录音结束，流结束，录音文件close。而pause是暂停，只是暂时停止录音流或播放流，稍后可以继续。可能你的框架中，stop起的就是pause的作用？

**Comment by molon** [comment]
@goodbless  呃  不好意思，理解错了。暂停的确是没有添加。 不好很抱歉，我最近没有什么时间优化这个。如果哥们有兴趣，可以帮忙改下，然后PR过来。 :)

**Comment by hulin12138** [comment]
求问所以现在找到了吗
