### ISSUE TITLE
播放在线amr问题，能分段缓存及时播放吗

### ISSUE THREAD

**Issue by yuyedaidao** [molon/MLAudioRecorder#6]
工程工amr文件是先缓存到本地再播放的，如果是较大的文件，整个缓存下来可能比较费时间，而且也没必要，我想问一下，能不能分段缓存及时播放。对音频不太了解，希望多多赐教

**Comment by molon** [comment]
@yuyedaidao   可以啊。但是取数据这块需要你自己搞下。取到相应的流数据然后实时解码播放。 demo里有录制时候获取流数据实时播放的例子。
