### ISSUE TITLE
怎么改成播放caf格式的文件呢？

### ISSUE THREAD

**Issue by hanleirx** [molon/MLAudioRecorder#9]
我试着改了一下，想播放caf文件，但没改成功，可能不是很了解你封装的过程，能不能写一个播放caf的啊，谢谢

**Comment by molon** [comment]
@hanleirx 这个库不维护啦。 播放caf实际上比播放amr简单多了，压根不需要转码的过程，参考`AmrPlayerReader`和`CafRecordWriter`仿写个`CafPlayerReader`出来。 
音频这块，建议去研究https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine2 这个是以后的主流。我这个库是练手之作，有诸多问题，封装方式和Amazing也是差很多。
